=== petrahillila/kauppa/xsd.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">
  <xs:element name="korttien-tiedot">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="kortti" maxOccurs="100">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="nimi" type="xs:string"/>
              <xs:element name="hinta" type="xs:decimal"/>
              <xs:element name="suunnittelija" type="xs:string"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== petrahillila/kauppa/tiedosto.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="xml_visuaalinen.xsl"?>

<korttien-tiedot
  xmlns="https://www.w3schools.com"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="https://www.w3schools.com xsd.xsd">
  <kortti>
  <nimi>Muumio</nimi>
  <hinta>3.20</hinta>
  <suunnittelija>Maicy Day</suunnittelija>
</kortti>
<kortti>
<nimi>Muumio</nimi>
<hinta>3.20</hinta>
<suunnittelija>Maicy Day</suunnittelija>
</kortti>
</korttien-tiedot>
